spring:
  application:
    name: CsvGenerator

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatnpay-delivery-status?createDatabaseIfNotExist=true&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: Abcmapp@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8070

destinationLocation : /home/logs/chatnpay/

logfilepath : /home/logs/chatnpay/csv-genarete



management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

# Alternative commented-out configuration:
# spring:
#   datasource:
#     url: jdbc:mysql://127.0.0.1:3306/chatnpay-delivery-status?createDatabaseIfNotExist=true&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
#     username: root
#     password: Abcmapp@123
#   jpa:
#     hibernate:
#       ddl-auto: update
